[package]
org = "ballerinax"
name = "persist.googlesheets"
version = "1.4.0"
authors = ["Ballerina"]
keywords = ["persist", "googlesheets", "experimental"]
repository = "https://github.com/ballerina-platform/module-ballerina-persist"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.googlesheets-native"
version = "1.4.0"
path = "../native/build/libs/persist.googlesheets-native-1.4.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist-native"
version = "1.4.0"
path = "./lib/persist-native-1.4.0-20240808-102300-3b855e5.jar"
